DROP DATABASE junkyarddb;

CREATE DATABASE junkyarddb WITH template=template0;
\connect junkyarddb;

ALTER DEFAULT PRIVILEGES GRANT ALL ON tables TO postgres;
ALTER DEFAULT PRIVILEGES GRANT ALL ON sequences TO postgres;

CREATE TABLE USERS (
id INTEGER PRIMARY KEY NOT NULL,
name VARCHAR(50) not null,
phone_number VARCHAR(30) NOT NULL,
email VARCHAR(30) NOT NULL,
password text NOT NULL
);

CREATE SEQUENCE users_seq increment 1 start 1;

CREATE TABLE GARAGE(
id INTEGER PRIMARY KEY NOT NULL,
name VARCHAR(50) NOT NULL,
location VARCHAR(100) NOT NULL,
operating_hour VARCHAR(200) NOT NULL,
details VARCHAR(500) NOT NULL
);

CREATE TABLE COMMENT(
id INTEGER PRIMARY KEY NOT NULL,
content VARCHAR(200) NOT NULL,
garageID INTEGER REFERENCES GARAGE(id),
userID INTEGER REFERENCES USERS(id)
);

